# https://firebase.google.com/docs/hosting/cloud-run#direct_requests_to_container
# https://cloud.google.com/run/docs/mapping-custom-domains
# https://cloud.google.com/run/docs/continuous-deployment-with-cloud-build

steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/coronavirus-tracker:$COMMIT_SHA", "."]
  # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/coronavirus-tracker:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "coronavirus-tracker"
      - "--image"
      - "gcr.io/$PROJECT_ID/coronavirus-tracker:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
images:
  - "gcr.io/$PROJECT_ID/coronavirus-tracker:$COMMIT_SHA"
